### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by io-taster** [d4rken/jt-dpm8600-psu-mqtt#2]
Compilation error: 'D2' was not declared in this scope

WiFiClient espClient;
PubSubClient client(espClient);

SoftwareSerial mySerial(D2, D1);
DPM8600 converter(1);

**Comment by d4rken** [comment]
Not using a WeMos d1 Mini or you have platform.io not configured correctly in vs code?
Either fix that or change the values to fit your board. 🤷

**Comment by io-taster** [comment]
Compilation error: 'D2' was not declared in this scope
SoftwareSerial mySerial(D2, D1);

What is D1 and D2?

**Comment by d4rken** [comment]
https://www.google.com/search?q=pinout+d1+mini

**Comment by io-taster** [comment]
Ok, i understand
Can i use an ESP32?

**Comment by io-taster** [comment]
I compile with Arduino IDE

**Comment by d4rken** [comment]
You have to figure that out yourself. 🙂
